version: '3'

services:
  api:
    container_name: api
    build: .
    restart: always
    ports:
      - 8080:8080
    depends_on: 
      - mongodb 

  mongodb:
    container_name: mongodb
    image: mongo:latest
    restart: always
    # environment:
    #   MONGO_INITDB_DATABASE: blog
    #   MONGO_INITDB_ROOT_USERNAME: root
    #   MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - '27017:27017'
    # volumes:
    #   - './dockervolume/mongodb:/data/db'
